# Generated by Django 5.2 on 2025-07-30 13:30

import _applib.model_choices_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[_applib.model_choices_fields.DOBValidator()]),
        ),
    ]
