# Generated by Django 5.2 on 2025-07-29 18:46

import _applib.model_choices_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('teacher_phone', models.CharField(max_length=11, unique=True, validators=[_applib.model_choices_fields.PhoneValidator()])),
                ('profile_picture', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DELETED', 'Deleted')], default='PENDING', max_length=15)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
            },
        ),
    ]
