# Generated by Django 5.2 on 2025-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
