# Generated by Django 5.2 on 2025-07-30 13:30

import _applib.model_choices_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teachermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[_applib.model_choices_fields.DOBValidator()]),
        ),
    ]
